#!/bin/bash

timestamp=$(date +"%Y%m%d%H%M%S")

DIR=/home/metta/git/zettel/$timestamp
TITLE=$1

if [[ $# -eq 0 ]]; 
then
	echo "Give this zet a title."
	exit 1
fi

echo "Zet title: $TITLE"

mkdir -p $DIR
touch $DIR/$timestamp.md
echo "# $TITLE" > $DIR/$timestamp.md
echo "" >> $DIR/$timestamp.md
echo "" >> $DIR/$timestamp.md
vim $DIR/$timestamp.md
